"""Programmatic access to the LOKF LinkML schema and its vocabulary.

The schema (``lokf.yaml``) and the published JSON-LD context are the single
source of truth for LOKF's types, typed-relation slots, and relation
vocabulary. This module reads them so tools never hardcode the vocabulary.

Both files are resolved in this order: an explicit ``path`` argument, a walk
up from the current directory for a repo checkout (so local edits always
win), then the copies packaged under ``lokf/data/`` (regenerated by
``lokf-build``) so installed wheels work outside a checkout.
"""
from __future__ import annotations

import json
import pathlib
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources

import yaml

_SCHEMA_NAME = "lokf.yaml"
_CONTEXT_NAME = "lokf.context.jsonld"


def _packaged(name: str) -> pathlib.Path | None:
    candidate = resources.files("lokf") / "data" / name
    try:
        p = pathlib.Path(str(candidate))
    except TypeError:  # zip-based install: no stable filesystem path
        return None
    return p if p.exists() else None


def _from_ancestors(name: str) -> pathlib.Path | None:
    cwd = pathlib.Path.cwd()
    for p in (cwd, *cwd.parents):
        if (p / name).exists():
            return p / name
    return None


def _resolve(name: str, path: str | pathlib.Path | None) -> pathlib.Path:
    """Resolve *name*: explicit path, then a checkout in an ancestor directory
    (so local schema edits always win), then the copy packaged with lokf."""
    if path is not None:
        return pathlib.Path(path)
    found = _from_ancestors(name) or _packaged(name)
    if found is None:
        raise FileNotFoundError(
            f"{name} not found: not in any ancestor of the current directory "
            "and not packaged with lokf"
        )
    return found


# Cached on the resolved absolute path, not the (path=None) argument, so a
# changed working directory re-resolves to a different file and reads fresh,
# while repeated calls from one location (e.g. the server hot path) are free.
@lru_cache(maxsize=None)
def _load_schema(resolved: str) -> dict:
    return yaml.safe_load(pathlib.Path(resolved).read_text(encoding="utf-8"))


@lru_cache(maxsize=None)
def _load_context(resolved: str) -> dict:
    return json.loads(pathlib.Path(resolved).read_text(encoding="utf-8"))["@context"]


def schema_path(path: str | pathlib.Path | None = None) -> pathlib.Path:
    """Resolve the LOKF schema file (``lokf.yaml``) to a filesystem path.

    Resolution order (same as every other reader here): an explicit *path*, a
    ``lokf.yaml`` found in the current directory or an ancestor, the the copy
    shipped inside the installed ``lokf`` package - so a bundle can be
    validated without a schema file of its own.
    """
    return _resolve(_SCHEMA_NAME, path)


def load_schema(path: str | pathlib.Path | None = None) -> dict:
    """Return the LOKF LinkML schema as a plain dict (cached per file)."""
    return _load_schema(str(_resolve(_SCHEMA_NAME, path)))


def load_context(path: str | pathlib.Path | None = None) -> dict:
    """Return the published JSON-LD ``@context`` mapping (cached per file)."""
    return _load_context(str(_resolve(_CONTEXT_NAME, path)))


@dataclass(frozen=True)
class Relation:
    """One relationship predicate: a frontmatter name bound to an RDF IRI."""

    name: str
    curie: str
    uri: str
    description: str
    is_slot: bool  # True: usable as a frontmatter key; False: via `relations:`
    domains: frozenset[str] = frozenset()  # classes declaring the slot; "Concept" = all

    def as_row(self) -> dict:
        """A JSON-serializable row (the ``lokf vocab --json`` / MCP shape)."""
        return {
            "name": self.name,
            "curie": self.curie,
            "uri": self.uri,
            "frontmatter_key": self.is_slot,
            "description": self.description,
        }


class Vocabulary:
    """The LOKF vocabulary derived from the LinkML schema."""

    def __init__(self, schema: dict):
        self._schema = schema
        self.prefixes: dict[str, str] = {
            k: v for k, v in schema.get("prefixes", {}).items()
        }
        self.classes: dict[str, str] = {
            name: cls.get("class_uri", f"lokf:{name}")
            for name, cls in schema.get("classes", {}).items()
        }
        # Typed-relation frontmatter keys: multivalued Concept-ranged slots
        # with a bound predicate, declared on Concept or one of its subclasses
        # (this includes Metric's `measures` and excludes structural slots
        # like KnowledgeBundle's `concepts` or Relation's `target`).
        classes = schema.get("classes", {})
        concept_classes = {
            name for name in classes if self._descends_from(classes, name, "Concept")
        }
        declared_in: dict[str, set[str]] = {}
        for cls_name in concept_classes:
            for slot_name in classes[cls_name].get("slots", []):
                declared_in.setdefault(slot_name, set()).add(cls_name)
        self.relation_slots: dict[str, Relation] = {}
        for name, slot in schema.get("slots", {}).items():
            if (
                slot.get("range") == "Concept"
                and slot.get("multivalued")
                and "slot_uri" in slot
                and name in declared_in
            ):
                curie = slot["slot_uri"]
                self.relation_slots[name] = Relation(
                    name=name,
                    curie=curie,
                    uri=self.expand(curie),
                    description=slot.get("description", "").strip(),
                    is_slot=True,
                    domains=frozenset(declared_in[name]),
                )
        self.relation_types: dict[str, Relation] = {}
        enum = schema.get("enums", {}).get("RelationType", {})
        for name, value in enum.get("permissible_values", {}).items():
            curie = value.get("meaning", f"lokf:{name}")
            self.relation_types[name] = Relation(
                name=name,
                curie=curie,
                uri=self.expand(curie),
                description=value.get("description", "").strip(),
                is_slot=name in self.relation_slots,
            )

    @staticmethod
    def _descends_from(classes: dict, name: str, ancestor: str) -> bool:
        while name is not None:
            if name == ancestor:
                return True
            name = classes.get(name, {}).get("is_a")
        return False

    def subclasses_of(self, ancestor: str) -> set[str]:
        """Class names descending from *ancestor* (inclusive), via ``is_a``."""
        classes = self._schema.get("classes", {})
        return {n for n in classes if self._descends_from(classes, n, ancestor)}

    def expand(self, curie: str) -> str:
        """Expand a ``prefix:local`` CURIE to a full IRI."""
        prefix, _, local = curie.partition(":")
        if local and prefix in self.prefixes:
            return self.prefixes[prefix] + local
        return curie

    def compact(self, uri: str) -> str:
        """Compact a full IRI to a CURIE where a prefix matches."""
        best = ""
        out = uri
        for prefix, ns in self.prefixes.items():
            if uri.startswith(ns) and len(ns) > len(best):
                best, out = ns, f"{prefix}:{uri[len(ns):]}"
        return out


@lru_cache(maxsize=None)
def _vocabulary(resolved: str) -> "Vocabulary":
    return Vocabulary(_load_schema(resolved))


def vocabulary(schema_path: str | pathlib.Path | None = None) -> Vocabulary:
    """Load the schema and return its :class:`Vocabulary` (cached per file)."""
    return _vocabulary(str(_resolve(_SCHEMA_NAME, schema_path)))
