"""Programmatic access to the LOKF LinkML schema and its vocabulary.

The schema (``lokf.yaml``) and the published JSON-LD context are the single
source of truth for LOKF's types, typed-relation slots, and relation
vocabulary. This module reads them so tools never hardcode the vocabulary.

Both files are resolved in this order: an explicit ``path`` argument, a walk
up from the current directory for a repo checkout (so local edits always
win), then the copies packaged under ``lokf/data/`` (regenerated by
``lokf-build``) so installed wheels work outside a checkout.
"""
from __future__ import annotations

import json
import pathlib
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources

import yaml

_SCHEMA_NAME = "lokf.yaml"
_CONTEXT_NAME = "lokf.context.jsonld"


def _packaged(name: str) -> pathlib.Path | None:
    candidate = resources.files("lokf") / "data" / name
    try:
        p = pathlib.Path(str(candidate))
    except TypeError:  # zip-based install: no stable filesystem path
        return None
    return p if p.exists() else None


def _from_ancestors(name: str) -> pathlib.Path | None:
    cwd = pathlib.Path.cwd()
    for p in (cwd, *cwd.parents):
        if (p / name).exists():
            return p / name
    return None


def _resolve(name: str, path: str | pathlib.Path | None) -> pathlib.Path:
    """Resolve *name*: explicit path, then a checkout in an ancestor directory
    (so local schema edits always win), then the copy packaged with lokf."""
    if path is not None:
        return pathlib.Path(path)
    found = _from_ancestors(name) or _packaged(name)
    if found is None:
        raise FileNotFoundError(
            f"{name} not found: not in any ancestor of the current directory "
            "and not packaged with lokf"
        )
    return found


# Cached on the resolved absolute path, not the (path=None) argument, so a
# changed working directory re-resolves to a different file and reads fresh,
# while repeated calls from one location (e.g. the server hot path) are free.
@lru_cache(maxsize=None)
def _load_schema(resolved: str) -> dict:
    return yaml.safe_load(pathlib.Path(resolved).read_text(encoding="utf-8"))


@lru_cache(maxsize=None)
def _load_context(resolved: str) -> dict:
    return json.loads(pathlib.Path(resolved).read_text(encoding="utf-8"))["@context"]


def schema_path(path: str | pathlib.Path | None = None) -> pathlib.Path:
    """Resolve the LOKF schema file (``lokf.yaml``) to a filesystem path.

    Resolution order (same as every other reader here): an explicit *path*, a
    ``lokf.yaml`` found in the current directory or an ancestor, the the copy
    shipped inside the installed ``lokf`` package - so a bundle can be
    validated without a schema file of its own.
    """
    return _resolve(_SCHEMA_NAME, path)


def load_schema(path: str | pathlib.Path | None = None) -> dict:
    """Return the LOKF LinkML schema as a plain dict (cached per file)."""
    return _load_schema(str(_resolve(_SCHEMA_NAME, path)))


def load_context(path: str | pathlib.Path | None = None) -> dict:
    """Return the published JSON-LD ``@context`` mapping (cached per file)."""
    return _load_context(str(_resolve(_CONTEXT_NAME, path)))


@dataclass(frozen=True)
class Relation:
    """One relationship predicate: a frontmatter name bound to an RDF IRI."""

    name: str
    curie: str
    uri: str
    description: str
    is_slot: bool  # True: usable as a frontmatter key; False: via `relations:`
    domains: frozenset[str] = frozenset()  # classes declaring the slot; "Concept" = all

    def as_row(self) -> dict:
        """A JSON-serializable row (the ``lokf vocab --json`` / MCP shape)."""
        return {
            "name": self.name,
            "curie": self.curie,
            "uri": self.uri,
            "frontmatter_key": self.is_slot,
            "description": self.description,
        }


class Vocabulary:
    """The LOKF vocabulary derived from the LinkML schema."""

    def __init__(self, schema: dict):
        self._schema = schema
        self.prefixes: dict[str, str] = {
            k: v for k, v in schema.get("prefixes", {}).items()
        }
        self.classes: dict[str, str] = {
            name: cls.get("class_uri", f"lokf:{name}")
            for name, cls in schema.get("classes", {}).items()
        }
        # Typed-relation frontmatter keys: multivalued Concept-ranged slots
        # with a bound predicate, declared on Concept or one of its subclasses
        # (this includes Metric's `measures` and excludes structural slots
        # like KnowledgeBundle's `concepts` or Relation's `target`).
        classes = schema.get("classes", {})
        concept_classes = {
            name for name in classes if self._descends_from(classes, name, "Concept")
        }
        declared_in: dict[str, set[str]] = {}
        for cls_name in concept_classes:
            for slot_name in classes[cls_name].get("slots", []):
                declared_in.setdefault(slot_name, set()).add(cls_name)
        self.relation_slots: dict[str, Relation] = {}
        for name, slot in schema.get("slots", {}).items():
            if (
                slot.get("range") == "Concept"
                and slot.get("multivalued")
                and "slot_uri" in slot
                and name in declared_in
            ):
                curie = slot["slot_uri"]
                self.relation_slots[name] = Relation(
                    name=name,
                    curie=curie,
                    uri=self.expand(curie),
                    description=slot.get("description", "").strip(),
                    is_slot=True,
                    domains=frozenset(declared_in[name]),
                )
        self.relation_types: dict[str, Relation] = {}
        enum = schema.get("enums", {}).get("RelationType", {})
        for name, value in enum.get("permissible_values", {}).items():
            curie = value.get("meaning", f"lokf:{name}")
            self.relation_types[name] = Relation(
                name=name,
                curie=curie,
                uri=self.expand(curie),
                description=value.get("description", "").strip(),
                is_slot=name in self.relation_slots,
            )

    @staticmethod
    def _descends_from(classes: dict, name: str, ancestor: str) -> bool:
        """Whether *name* reaches *ancestor* via ``is_a`` or ``mixins``."""
        seen: set[str] = set()
        stack = [name]
        while stack:
            n = stack.pop()
            if n is None or n in seen:
                continue
            seen.add(n)
            if n == ancestor:
                return True
            cls = classes.get(n) or {}
            parent = cls.get("is_a")
            if parent:
                stack.append(parent)
            stack.extend(cls.get("mixins") or [])
        return False

    def subclasses_of(self, ancestor: str) -> set[str]:
        """Class names descending from *ancestor* (inclusive), via ``is_a``."""
        classes = self._schema.get("classes", {})
        return {n for n in classes if self._descends_from(classes, n, ancestor)}

    def expand(self, curie: str) -> str:
        """Expand a ``prefix:local`` CURIE to a full IRI."""
        prefix, _, local = curie.partition(":")
        if local and prefix in self.prefixes:
            return self.prefixes[prefix] + local
        return curie

    def compact(self, uri: str) -> str:
        """Compact a full IRI to a CURIE where a prefix matches."""
        best = ""
        out = uri
        for prefix, ns in self.prefixes.items():
            if uri.startswith(ns) and len(ns) > len(best):
                best, out = ns, f"{prefix}:{uri[len(ns):]}"
        return out

    #: The `slot_usage` keys a class row reports. Everything a client needs to
    #: write a valid value where a class narrows a slot (Source.author is a
    #: single patterned string, not the Agent list the top-level slot says);
    #: loader mechanics such as `inlined_as_list` and `implements` stay out.
    _USAGE_KEYS = ("range", "multivalued", "pattern", "required", "recommended", "description")

    def class_docs(self) -> list[dict]:
        """Every non-abstract class, each with its schema description and
        aliases. ``is_type_value`` marks the subset that is also valid in a
        Concept's `type:` field (Concept/Agent descendants); the rest are
        embedded object shapes (e.g. Parameter, Source, Verification) that
        only ever appear nested under another concept's slots. ``slot_usage``
        carries the class's own narrowing of a slot, and its `recommended`
        fields, which no generated artifact otherwise reports."""
        classes = self._schema.get("classes", {})
        out: list[dict] = []
        for name, cls in classes.items():
            cls = cls or {}
            if cls.get("abstract"):
                continue
            is_type_value = self._descends_from(
                classes, name, "Concept"
            ) or self._descends_from(classes, name, "Agent")
            curie = self.classes[name]
            row: dict = {
                "name": name,
                "curie": curie,
                "uri": self.expand(curie),
                "is_type_value": is_type_value,
            }
            desc = (cls.get("description") or "").strip()
            if desc:
                row["description"] = desc
            if cls.get("aliases"):
                row["aliases"] = list(cls["aliases"])
            usage = {}
            for slot_name, override in (cls.get("slot_usage") or {}).items():
                kept = {k: override[k] for k in self._USAGE_KEYS if k in (override or {})}
                if "description" in kept:
                    kept["description"] = str(kept["description"]).strip()
                if kept:
                    usage[slot_name] = kept
            if usage:
                row["slot_usage"] = usage
            out.append(row)
        return out

    @staticmethod
    def _slot_row(name: str, slot: dict, class_name: str | None = None) -> dict | None:
        slot = slot or {}
        desc = (slot.get("description") or "").strip()
        if not desc:
            return None
        row: dict = {"name": name, "description": desc}
        if class_name:
            row["class"] = class_name
        if slot.get("range"):
            row["range"] = slot["range"]
        if slot.get("multivalued"):
            row["multivalued"] = True
        if slot.get("required"):
            row["required"] = True
        if slot.get("pattern"):
            row["pattern"] = slot["pattern"]
        if slot.get("aliases"):
            row["aliases"] = list(slot["aliases"])
        return row

    def slot_docs(self) -> list[dict]:
        """Every schema slot that carries a description - the frontmatter field
        reference, with each slot's range, multivalued flag, `required` and
        `pattern` where set, so a client that cannot run `lokf validate` can
        still check a value. A slot a class redefines locally under its own
        `attributes:` (e.g. Parameter.type, Source.id) is emitted as an
        additional row carrying `class`, so that class's own description isn't
        shadowed by the generic top-level one; a `slot_usage` narrowing is
        reported on the class row instead."""
        out: list[dict] = []
        for name, slot in (self._schema.get("slots") or {}).items():
            row = self._slot_row(name, slot)
            if row:
                out.append(row)
        for cls_name, cls in (self._schema.get("classes") or {}).items():
            attrs = (cls or {}).get("attributes") or {}
            for name, attr in attrs.items():
                row = self._slot_row(name, attr, class_name=cls_name)
                if row:
                    out.append(row)
        return out

    def enum_values(self, enum_name: str) -> list[dict]:
        """A schema enum's permissible values, each with its meaning (CURIE/IRI),
        description, and aliases where the schema gives them. A value with no
        explicit `meaning` falls back to a minted `lokf:<value>` term, matching
        `relation_types`' convention - so the same RelationType value reports
        the same curie/uri from `vocab.relation_types` and from here."""
        enum = (self._schema.get("enums", {}) or {}).get(enum_name, {}) or {}
        out: list[dict] = []
        for value, defn in (enum.get("permissible_values") or {}).items():
            defn = defn or {}
            meaning = defn.get("meaning", f"lokf:{value}")
            row: dict = {"value": value, "curie": meaning, "uri": self.expand(meaning)}
            desc = (defn.get("description") or "").strip()
            if desc:
                row["description"] = desc
            if defn.get("aliases"):
                row["aliases"] = list(defn["aliases"])
            out.append(row)
        return out

    def manifest(self) -> dict:
        """The full vocabulary as a JSON-serializable manifest - classes, slots,
        and the value enums, each carrying the schema's own descriptions. The
        machine-readable reference a downstream tool (an editor's field help, a
        docs site) consumes instead of parsing ``lokf.yaml`` or the generated
        JSON Schema itself."""
        return {
            "schema_version": str(self._schema.get("version", "")),
            "classes": self.class_docs(),
            "slots": self.slot_docs(),
            "enums": {
                name: self.enum_values(name)
                for name in self._schema.get("enums", {})
            },
        }


@lru_cache(maxsize=None)
def _vocabulary(resolved: str) -> "Vocabulary":
    return Vocabulary(_load_schema(resolved))


def vocabulary(schema_path: str | pathlib.Path | None = None) -> Vocabulary:
    """Load the schema and return its :class:`Vocabulary` (cached per file)."""
    return _vocabulary(str(_resolve(_SCHEMA_NAME, schema_path)))
