"""Programmatic access to the LOKF LinkML schema and its vocabulary.

The schema (``lokf.yaml``) and the published JSON-LD context are the single
source of truth for LOKF's types, typed-relation slots, and relation
vocabulary. This module reads them so tools never hardcode the vocabulary.

Both files are resolved in this order: an explicit ``path`` argument, a walk
up from the current directory for a repo checkout (so local edits always
win), then the copies packaged under ``lokf/data/`` (regenerated by
``lokf-build``) so installed wheels work outside a checkout.
"""
from __future__ import annotations

import json
import pathlib
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources

import yaml

_SCHEMA_NAME = "lokf.yaml"
_CONTEXT_NAME = "lokf.context.jsonld"


def _packaged(name: str) -> pathlib.Path | None:
    candidate = resources.files("lokf") / "data" / name
    try:
        p = pathlib.Path(str(candidate))
    except TypeError:  # zip-based install: no stable filesystem path
        return None
    return p if p.exists() else None


def _from_ancestors(name: str) -> pathlib.Path | None:
    cwd = pathlib.Path.cwd()
    for p in (cwd, *cwd.parents):
        if (p / name).exists():
            return p / name
    return None


def _resolve(name: str, path: str | pathlib.Path | None) -> pathlib.Path:
    """Resolve *name*: explicit path, then a checkout in an ancestor directory
    (so local schema edits always win), then the copy packaged with lokf."""
    if path is not None:
        return pathlib.Path(path)
    found = _from_ancestors(name) or _packaged(name)
    if found is None:
        raise FileNotFoundError(
            f"{name} not found: not in any ancestor of the current directory "
            "and not packaged with lokf"
        )
    return found


# Cached on the resolved absolute path, not the (path=None) argument, so a
# changed working directory re-resolves to a different file and reads fresh,
# while repeated calls from one location (e.g. the server hot path) are free.
@lru_cache(maxsize=None)
def _load_schema(resolved: str) -> dict:
    return yaml.safe_load(pathlib.Path(resolved).read_text(encoding="utf-8"))


@lru_cache(maxsize=None)
def _load_context(resolved: str) -> dict:
    return json.loads(pathlib.Path(resolved).read_text(encoding="utf-8"))["@context"]


def schema_path(path: str | pathlib.Path | None = None) -> pathlib.Path:
    """Resolve the LOKF schema file (``lokf.yaml``) to a filesystem path.

    Resolution order (same as every other reader here): an explicit *path*, a
    ``lokf.yaml`` found in the current directory or an ancestor, the the copy
    shipped inside the installed ``lokf`` package - so a bundle can be
    validated without a schema file of its own.
    """
    return _resolve(_SCHEMA_NAME, path)


def project_schema(start: str | pathlib.Path | None = None) -> pathlib.Path | None:
    """The domain schema the project declares, or ``None``.

    A project names it once, in the ``pyproject.toml`` that already pins
    ``lokf``, so every command reads the same file without a ``--schema`` on
    each call::

        [tool.lokf]
        schema = "domain.yaml"   # relative to this file

    *start* is the bundle or concept file a command was given; the nearest
    ``pyproject.toml`` with a ``[tool.lokf]`` table, from there upwards,
    decides. The schema is the bundle's project's, wherever the shell is, and
    a bundle reached through a link (``knowledge_bundle -> .lokf/knowledge``)
    is searched where it really lives. Without *start*, the search runs from
    the working directory. A declared file that does not exist raises
    :class:`FileNotFoundError`: validating against core ``lokf.yaml`` instead
    would pass a bundle the project meant to check more strictly.
    """
    try:
        import tomllib
    except ModuleNotFoundError:  # Python 3.10
        import tomli as tomllib
    base = pathlib.Path(start).resolve() if start is not None else pathlib.Path.cwd()
    if base.is_file():
        base = base.parent
    for d in (base, *base.parents):
        f = d / "pyproject.toml"
        if not f.exists():
            continue
        try:
            tool = tomllib.loads(f.read_text(encoding="utf-8")).get("tool", {}).get("lokf")
        except tomllib.TOMLDecodeError as exc:
            raise ValueError(f"{f}: {exc}") from exc
        if not isinstance(tool, dict):
            continue
        name = tool.get("schema")
        if name is None:
            return None
        if not isinstance(name, str):
            raise ValueError(f"{f}: [tool.lokf] schema must be a path string, not {name!r}")
        schema = d / name
        if not schema.is_file():
            raise FileNotFoundError(f"{f} names schema {name}, which does not exist at {schema}")
        return schema
    return None


def domain_schema(
    explicit: str | pathlib.Path | None = None, start: str | pathlib.Path | None = None
) -> pathlib.Path | None:
    """The domain schema a command validates or projects under: *explicit*
    (``--schema``) when given, else the one the project around *start*
    declares (:func:`project_schema`), else ``None`` for core LOKF."""
    if explicit is not None:
        return pathlib.Path(explicit)
    return project_schema(start)


def load_schema(path: str | pathlib.Path | None = None) -> dict:
    """Return the LOKF LinkML schema as a plain dict (cached per file)."""
    return _load_schema(str(_resolve(_SCHEMA_NAME, path)))


def load_context(path: str | pathlib.Path | None = None) -> dict:
    """Return the published JSON-LD ``@context`` mapping (cached per file)."""
    return _load_context(str(_resolve(_CONTEXT_NAME, path)))


# ParameterType values, each naming the lokf Parameter-kind class it expands to.
_PARAMETER_KINDS = {
    "string": "StringParameter", "integer": "IntegerParameter",
    "number": "NumberParameter", "boolean": "BooleanParameter",
    "date": "DateParameter", "datetime": "DatetimeParameter",
    "time": "TimeParameter", "uri": "UriParameter", "json": "JsonParameter",
}


def authoring_context(context: dict) -> dict:
    """Return a ``gen-jsonld-context`` ``@context`` mapping made fit for OKF
    frontmatter. ``lokf-build`` publishes LOKF's own context this way, and
    :func:`schema_context` builds a domain schema's the same way."""
    ctx = dict(context)
    # Two standard JSON-LD keyword aliases make unmodified OKF frontmatter
    # behave as Linked Data: `type` designates the RDF class, `id` the subject.
    ctx["type"] = "@type"
    ctx["id"] = "@id"
    # ParameterType values sit in @type position (Parameter's `type` key shares
    # the alias above), so each authoring value must expand to its designed
    # lokf Parameter-kind class — gen-jsonld-context does not emit enum-meaning
    # terms. Same mechanism by which class names like "Metric" expand as @type.
    for value, cls in _PARAMETER_KINDS.items():
        ctx[value] = {"@id": f"https://w3id.org/lokf/{cls}"}
    # `author` must NOT be @id-coerced: OKF §7 actor strings ("team:ga4-docs",
    # "human:kliu") are literals, and coercion would silently mint IRIs in
    # unregistered URI schemes. Inlined Agent objects are unaffected.
    if isinstance(ctx.get("author"), dict):
        ctx["author"] = {k: v for k, v in ctx["author"].items() if k != "@type"}
    return ctx


@lru_cache(maxsize=None)
def _schema_context(resolved: str) -> dict:
    from linkml.generators.jsonldcontextgen import ContextGenerator

    generated = json.loads(ContextGenerator(resolved).serialize())["@context"]
    ctx = authoring_context(generated)
    # The generated @vocab is the domain's namespace, and the domain's own
    # terms are written relative to it. Make those absolute, then fall back to
    # LOKF's @vocab, so a key no schema declares projects as it does without
    # a schema, not as a term the domain never declared.
    vocab, core = ctx.get("@vocab"), load_context()["@vocab"]
    if vocab and vocab != core:
        for key, value in ctx.items():
            if isinstance(value, dict) and _vocab_relative(value.get("@id")):
                ctx[key] = {**value, "@id": vocab + value["@id"]}
            elif _vocab_relative(value):
                ctx[key] = vocab + value
        ctx["@vocab"] = core
    return ctx


def _vocab_relative(iri: object) -> bool:
    """Whether a context's ``@id`` value is relative to its ``@vocab``: neither
    a keyword nor a CURIE or IRI."""
    return isinstance(iri, str) and not iri.startswith("@") and ":" not in iri


def schema_context(schema_path: str | pathlib.Path | None = None) -> dict:
    """Return the ``@context`` that projects a bundle under *schema_path*.

    With no *schema_path*, this is the published context
    (:func:`load_context`). A domain schema that ``imports: [lokf]`` gets a
    context generated from it, so its classes and slots expand to their own
    IRIs rather than to ``lokf:`` terms. Generating one needs LinkML (the
    ``build`` extra).
    """
    if schema_path is None:
        return load_context()
    return _schema_context(str(pathlib.Path(schema_path).resolve()))


@dataclass(frozen=True)
class Relation:
    """One relationship predicate: a frontmatter name bound to an RDF IRI."""

    name: str
    curie: str
    uri: str
    description: str
    is_slot: bool  # True: usable as a frontmatter key; False: via `relations:`
    domains: frozenset[str] = frozenset()  # classes declaring the slot; "Concept" = all

    def as_row(self) -> dict:
        """A JSON-serializable row (the ``lokf vocab --json`` / MCP shape)."""
        return {
            "name": self.name,
            "curie": self.curie,
            "uri": self.uri,
            "frontmatter_key": self.is_slot,
            "description": self.description,
        }


class Vocabulary:
    """The LOKF vocabulary derived from the LinkML schema."""

    def __init__(self, schema: dict):
        self._schema = schema
        self.prefixes: dict[str, str] = {
            k: v for k, v in schema.get("prefixes", {}).items()
        }
        self.classes: dict[str, str] = {
            name: cls.get("class_uri", f"lokf:{name}")
            for name, cls in schema.get("classes", {}).items()
        }
        # A relation is a frontmatter key that holds concept ids, is
        # multivalued and has a slot_uri. A Concept class must declare it, or
        # inherit it from a class outside Concept. Metric's `measures` counts;
        # structural slots like KnowledgeBundle's `concepts` and Relation's
        # `target` do not. A slot holds concept ids on a class if its range
        # there, after slot_usage, is Concept or a subclass, or if one of its
        # `any_of` ranges is. So a domain schema can turn an imported slot into
        # a relation with slot_usage. A class's `attributes` count as its slots.
        self._classes = schema.get("classes") or {}
        self._slots = schema.get("slots") or {}
        classes = self._classes
        self._concept_classes = concept_classes = {
            name for name in classes if self._descends_from(classes, name, "Concept")
        }
        declared_in: dict[str, set[str]] = {}
        for cls_name in concept_classes:
            for owner in self._ancestors(classes, cls_name):
                if owner != cls_name and owner in concept_classes:
                    continue  # declares its own slots itself
                cls = classes.get(owner) or {}
                for slot_name in (
                    *(cls.get("slots") or []),
                    *(cls.get("slot_usage") or {}),
                    *(cls.get("attributes") or {}),
                ):
                    declared_in.setdefault(slot_name, set()).add(cls_name)
        #: Every slot a Concept class holds concept ids in, single- or
        #: multivalued, with the classes that do: what `--check-refs` reads.
        self.reference_slots: dict[str, frozenset[str]] = {}
        self.relation_slots: dict[str, Relation] = {}
        # Schema-level slots in their order, then slots only attributes declare
        for name in (*self._slots, *sorted(set(declared_in) - set(self._slots))):
            induced = {c: self._induced(c, name) for c in declared_in.get(name, ())}
            refs = frozenset(c for c, s in induced.items() if self._holds_concepts(s))
            if not refs:
                continue
            slot = self._definition(min(refs), name)
            self.reference_slots[name] = refs
            domains = frozenset(c for c in refs if induced[c]["multivalued"])
            if domains and "slot_uri" in slot:
                curie = slot["slot_uri"]
                self.relation_slots[name] = Relation(
                    name=name,
                    curie=curie,
                    uri=self.expand(curie),
                    description=(slot.get("description") or "").strip(),
                    is_slot=True,
                    domains=domains,
                )
        self.relation_types: dict[str, Relation] = {}
        enum = schema.get("enums", {}).get("RelationType", {})
        for name, value in enum.get("permissible_values", {}).items():
            curie = value.get("meaning", f"lokf:{name}")
            self.relation_types[name] = Relation(
                name=name,
                curie=curie,
                uri=self.expand(curie),
                description=value.get("description", "").strip(),
                is_slot=name in self.relation_slots,
            )

    @staticmethod
    def _ancestors(elements: dict, name: str) -> list[str]:
        """*name* and every class or slot it inherits from, in LinkML's order
        (``SchemaView.class_ancestors``): depth first, an element's mixins
        before its ``is_a``, each listed where first reached."""
        order, todo = [name], [name]
        while todo:
            element = elements.get(todo.pop()) or {}
            for parent in (*(element.get("mixins") or []), element.get("is_a")):
                if parent and parent not in order:
                    order.append(parent)
                    todo.append(parent)
        return order

    def _attribute(self, cls_name: str, name: str) -> dict | None:
        """The attribute *name* that class *cls_name* declares or inherits:
        the first along its ancestors, as LinkML takes it."""
        for c in self._ancestors(self._classes, cls_name):
            attribute = ((self._classes.get(c) or {}).get("attributes") or {}).get(name)
            if attribute is not None:
                return attribute
        return None

    def _definition(self, cls_name: str, name: str) -> dict:
        """Slot *name* as class *cls_name* defines it before slot_usage: its
        attribute if it has one, else the schema-level slot."""
        attribute = self._attribute(cls_name, name)
        return attribute if attribute is not None else self._slots.get(name) or {}

    def _induced(self, cls_name: str, name: str) -> dict:
        """The ``range``, ``multivalued`` and ``any_of`` ranges class
        *cls_name* gives slot *name*, as ``SchemaView.induced_slot`` resolves
        them: the first slot_usage value along the class's ancestors, else the
        attribute, else the first along the slot's own ancestors, else, for
        ``range``, the schema's ``default_range``."""
        usages = [
            ((self._classes.get(c) or {}).get("slot_usage") or {}).get(name) or {}
            for c in self._ancestors(self._classes, cls_name)
        ]
        attribute = self._attribute(cls_name, name)
        definitions = (
            [attribute]
            if attribute is not None
            else [self._slots.get(s) or {} for s in self._ancestors(self._slots, name)]
        )
        induced = {}
        for key in ("range", "multivalued", "any_of"):
            induced[key] = next(
                (u[key] for u in usages if u.get(key) not in (None, "", [], {})),
                next((d[key] for d in definitions if d.get(key)), None),
            )
        induced["range"] = induced["range"] or self._schema.get("default_range")
        induced["any_of"] = [e.get("range") for e in induced["any_of"] or []]
        return induced

    def _holds_concepts(self, induced: dict) -> bool:
        """Whether an induced slot's range, or one of its ``any_of`` ranges,
        is Concept or a subclass."""
        return any(r in self._concept_classes for r in (induced["range"], *induced["any_of"]))

    @classmethod
    def _descends_from(cls, classes: dict, name: str, ancestor: str) -> bool:
        """Whether *name* reaches *ancestor* via ``is_a`` or ``mixins``."""
        return ancestor in cls._ancestors(classes, name)

    def references(self, type_name: str) -> set[str]:
        """The slots a concept of *type_name* holds concept ids in. A type no
        class declares is a plain Concept (SPEC §8), so it gets Concept's."""
        if type_name not in self._classes:
            type_name = "Concept"
        ancestors = self._ancestors(self._classes, type_name)
        return {
            name
            for name, holders in self.reference_slots.items()
            # Inherited from a holder, and not narrowed to a string since
            if not holders.isdisjoint(ancestors)
            and self._holds_concepts(self._induced(type_name, name))
        }

    def subclasses_of(self, ancestor: str) -> set[str]:
        """Class names descending from *ancestor* (inclusive), via ``is_a``."""
        classes = self._schema.get("classes", {})
        return {n for n in classes if self._descends_from(classes, n, ancestor)}

    def expand(self, curie: str) -> str:
        """Expand a ``prefix:local`` CURIE to a full IRI."""
        prefix, _, local = curie.partition(":")
        if local and prefix in self.prefixes:
            return self.prefixes[prefix] + local
        return curie

    def compact(self, uri: str) -> str:
        """Compact a full IRI to a CURIE where a prefix matches."""
        best = ""
        out = uri
        for prefix, ns in self.prefixes.items():
            if uri.startswith(ns) and len(ns) > len(best):
                best, out = ns, f"{prefix}:{uri[len(ns):]}"
        return out

    #: The `slot_usage` keys a class row reports. Everything a client needs to
    #: write a valid value where a class narrows a slot (Source.author is a
    #: single patterned string, not the Agent list the top-level slot says);
    #: loader mechanics such as `inlined_as_list` and `implements` stay out.
    _USAGE_KEYS = ("range", "multivalued", "pattern", "required", "recommended", "description")

    def class_docs(self) -> list[dict]:
        """Every non-abstract class, each with its schema description and
        aliases. ``is_type_value`` marks the subset that is also valid in a
        Concept's `type:` field (Concept/Agent descendants); the rest are
        embedded object shapes (e.g. Parameter, Source, Verification) that
        only ever appear nested under another concept's slots. ``slot_usage``
        carries the class's own narrowing of a slot, and its `recommended`
        fields, which no generated artifact otherwise reports."""
        classes = self._schema.get("classes", {})
        out: list[dict] = []
        for name, cls in classes.items():
            cls = cls or {}
            if cls.get("abstract"):
                continue
            is_type_value = self._descends_from(
                classes, name, "Concept"
            ) or self._descends_from(classes, name, "Agent")
            curie = self.classes[name]
            row: dict = {
                "name": name,
                "curie": curie,
                "uri": self.expand(curie),
                "is_type_value": is_type_value,
            }
            desc = (cls.get("description") or "").strip()
            if desc:
                row["description"] = desc
            if cls.get("aliases"):
                row["aliases"] = list(cls["aliases"])
            usage = {}
            for slot_name, override in (cls.get("slot_usage") or {}).items():
                kept = {k: override[k] for k in self._USAGE_KEYS if k in (override or {})}
                if "description" in kept:
                    kept["description"] = str(kept["description"]).strip()
                if kept:
                    usage[slot_name] = kept
            if usage:
                row["slot_usage"] = usage
            out.append(row)
        return out

    @staticmethod
    def _slot_row(name: str, slot: dict, class_name: str | None = None) -> dict | None:
        slot = slot or {}
        desc = (slot.get("description") or "").strip()
        if not desc:
            return None
        row: dict = {"name": name, "description": desc}
        if class_name:
            row["class"] = class_name
        if slot.get("range"):
            row["range"] = slot["range"]
        if slot.get("multivalued"):
            row["multivalued"] = True
        if slot.get("required"):
            row["required"] = True
        if slot.get("pattern"):
            row["pattern"] = slot["pattern"]
        if slot.get("aliases"):
            row["aliases"] = list(slot["aliases"])
        return row

    def slot_docs(self) -> list[dict]:
        """Every schema slot that carries a description - the frontmatter field
        reference, with each slot's range, multivalued flag, `required` and
        `pattern` where set, so a client that cannot run `lokf validate` can
        still check a value. A slot a class redefines locally under its own
        `attributes:` (e.g. Parameter.type, Source.id) is emitted as an
        additional row carrying `class`, so that class's own description isn't
        shadowed by the generic top-level one; a `slot_usage` narrowing is
        reported on the class row instead."""
        out: list[dict] = []
        for name, slot in (self._schema.get("slots") or {}).items():
            row = self._slot_row(name, slot)
            if row:
                out.append(row)
        for cls_name, cls in (self._schema.get("classes") or {}).items():
            attrs = (cls or {}).get("attributes") or {}
            for name, attr in attrs.items():
                row = self._slot_row(name, attr, class_name=cls_name)
                if row:
                    out.append(row)
        return out

    def enum_values(self, enum_name: str) -> list[dict]:
        """A schema enum's permissible values, each with its meaning (CURIE/IRI),
        description, and aliases where the schema gives them. A value with no
        explicit `meaning` falls back to a minted `lokf:<value>` term, matching
        `relation_types`' convention - so the same RelationType value reports
        the same curie/uri from `vocab.relation_types` and from here."""
        enum = (self._schema.get("enums", {}) or {}).get(enum_name, {}) or {}
        out: list[dict] = []
        for value, defn in (enum.get("permissible_values") or {}).items():
            defn = defn or {}
            meaning = defn.get("meaning", f"lokf:{value}")
            row: dict = {"value": value, "curie": meaning, "uri": self.expand(meaning)}
            desc = (defn.get("description") or "").strip()
            if desc:
                row["description"] = desc
            if defn.get("aliases"):
                row["aliases"] = list(defn["aliases"])
            out.append(row)
        return out

    def manifest(self) -> dict:
        """The full vocabulary as a JSON-serializable manifest - classes, slots,
        and the value enums, each carrying the schema's own descriptions. The
        machine-readable reference a downstream tool (an editor's field help, a
        docs site) consumes instead of parsing ``lokf.yaml`` or the generated
        JSON Schema itself."""
        return {
            "schema_version": str(self._schema.get("version", "")),
            "classes": self.class_docs(),
            "slots": self.slot_docs(),
            "enums": {
                name: self.enum_values(name)
                for name in self._schema.get("enums", {})
            },
        }


def _follows(imported: str) -> bool:
    """Return True if this import can add to the vocabulary. LinkML's own
    schemas, such as ``linkml:types``, define only types, and
    :class:`Vocabulary` does not read types."""
    return not imported.startswith("linkml:")


def _with_imports(resolved: str) -> dict:
    """Merge the schema at *resolved* with every schema it imports, and return
    one dict in the raw YAML shape that :class:`Vocabulary` reads.

    A domain schema that ``imports: [lokf]`` usually defines none of LOKF's
    slots itself, so reading only its own file finds no relation slots.
    SchemaView resolves each import against the directory of the file that
    imports it. When two schemas define the same name, the later one in the
    closure wins. The importing schema comes last, so its own definitions win.
    """
    from linkml_runtime.dumpers import json_dumper
    from linkml_runtime.utils.schemaview import SchemaView

    view = SchemaView(resolved)
    merged = dict(_load_schema(resolved))
    for key in ("prefixes", "classes", "slots", "enums"):
        merged[key] = {}
    for name in view.imports_closure():
        if not _follows(name):
            continue
        part = json_dumper.to_dict(view.schema_map[name])
        for key in ("classes", "slots", "enums"):
            merged[key].update(part.get(key) or {})
        # The dump stores each prefix as a {prefix_prefix, prefix_reference}
        # object. Keep only the IRI, as the raw YAML does.
        merged["prefixes"].update(
            (k, v["prefix_reference"] if isinstance(v, dict) else v)
            for k, v in (part.get("prefixes") or {}).items()
        )
    return merged


@lru_cache(maxsize=None)
def _vocabulary(resolved: str) -> "Vocabulary":
    schema = _load_schema(resolved)
    # Merge only when the schema imports more than LinkML's own schemas.
    # Stock lokf.yaml imports only linkml:types, so it is still read as one file.
    if any(_follows(str(i)) for i in schema.get("imports") or []):
        schema = _with_imports(resolved)
    return Vocabulary(schema)


def vocabulary(schema_path: str | pathlib.Path | None = None) -> Vocabulary:
    """Return the :class:`Vocabulary` of the schema and every schema it
    imports (cached per file)."""
    return _vocabulary(str(_resolve(_SCHEMA_NAME, schema_path)))
